
//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "warga",
    "email": "warga@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "warga"
}


//login
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "warga@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/me
Content-Type: application/application/json


###
DELETE http://localhost:5000/logout
Content-Type: application/json


# berita
###
GET http://localhost:5000/berita HTTP/1.1
Content-Type: application/json


###
POST http://localhost:5000/berita
Content-Type: application/json

{
    "title": "Sampah Menumpuk",
    "content": "Diduga mamang tukang sampah digaji dibawah UMR, si mamang melakukan mogok kerja yang membuat sampah di perum sugan rame menumpuk"
}

###
GET http://localhost:5000/berita/edfe0647-b4ad-4ac3-917b-e4ab78aa0d33
Content-Type: application/json



//Profile
###
GET http://localhost:5000/profile HTTP/1.1
Content-Type: application/json

###
POST http://localhost:5000/profile
Content-Type: application/json

{
    "name": "Warga",
    "gender": "Male",
    "noKtp": "245324234553255",
    "noRumah": "40",
    "birthDate": "22 Juni 2002"
}

###
PATCH http://localhost:5000/profile/update
Content-Type: application/json

{
    "name": "Warga",
    "gender": "Female",
    "noKtp": "11111111111111111",
    "noRumah": "40",
    "birthDate": "22 Juni 2002"
}